server:
  port: 8080

spring:
  application:
    name: message-center-test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/message_center?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: jason2004

  data:
    redis:
      host: localhost
      port: 6379
      password: jason2004
      database: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: jason2004
    virtual-host: /

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: warn
    com.dasi: debug
    com.zaxxer.hikari: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}: %msg%n"