server:
  port: 8080

spring:
  application:
    name: message-center-test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/message_center?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: jason2004

  jackson:
    time-zone: Asia/Shanghai

  data:
    redis:
      host: localhost
      port: 6379
      password: jason2004
      database: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: jason2004
    virtual-host: /message_center

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  level:
    root: warn
    com.dasi: debug
    com.zaxxer: error
    com.baomidou.mybatisplus: error
    org.mybatis: error
  pattern:
    console: "%d{MM-dd HH:mm:ss} %-5level %-30logger{2} - %msg%n"

dasi:
  jwt:
    secret-key: dasi0227dasi0227dasi0227dasi0227dasi0227dasi0227dasi0227dasi0227
    token-name: Authorization
    claim-user-key: userId
    signature-algorithm: HS512
    token-ttl: 720000000